### ISSUE TITLE
Indented blocks should be highlighted explicitly as one block

### ISSUE THREAD

**Issue by Ibmurai** [bobthecow/Markdown.mode#1]
(My php docblocks are partially, incorrectly highlighted...)

The indented blocks should be highlighted explicitly as one block.

**Comment by bobthecow** [comment]
Can you give me an example of text that fails to highlight properly, and perhaps a screenshot of what you get instead?

Thanks!

**Comment by Ibmurai** [comment]
Heres some text:

# Test
- salmon
- some fish

And this PHP block:

```
<?php
/**
 * Doc comment
 *
 * @param mixed $fancy
 */
function getAnswer() {
    return 42;
} 
?>
```

See how the PHP block is strangely highlighted?

Also lists have a tendency to sometimes not highlight the last bullet (fiddling with the trailing newline solves it):
- salmon
- some fish
- some fish

And in plain text:

```
Test
====

  * salmon
  * some fish

And this PHP block:

    <?php
    /**
     * Doc comment
     *
     * @param mixed $fancy
     */
    function getAnswer() {
        return 42;
    } 
    ?>

See how the PHP block is strangely highlighted?

Also lists have a tendency to sometimes not highlight the last bullet (fiddling with the trailing newline solves it):

  * salmon
  * some fish
  * some fish
```

And a link to a screenshot:
http://dl.dropbox.com/u/10855176/Images/MarkdownSyntaxProblem.png

I have some experience writing syntax modes for Coda myself, and I know it can be quite... Iffy... ;)

**Comment by bobthecow** [comment]
i think i got both of those issues fixed. mind testing out the dev branch a bit with some of your markdown files?

**Comment by Ibmurai** [comment]
I'm happy! Thanks :)

...Still I'm just gonna point two things out. Feel free to ignore them, or reopen if you please.

From [Daring Fireball Markdown: Syntax](http://daringfireball.net/projects/markdown/syntax):

> List markers typically start at the left margin, but may be indented by up to three spaces. 
> List markers must be followed by one or more spaces or a tab.

Below is an example and [here's a link to a screenshot](http://dl.dropbox.com/u/10855176/Images/lists_nitpicking.png):

```
  * Good...
    This is a part of the bullet above, but it isn't highlighted.
  * Good
   * Good
    * this has four spaces in front and should not be highlighted
     * this is, correctly not highlighted
```

**Comment by bobthecow** [comment]
Hrm. But only if there's an even number of line breaks between it and the previous bullet:

![wtf?](http://i.justinhileman.info/Untitled.md-20110823-233950.png)

**Comment by Ibmurai** [comment]
Good times! ;)

I wish I had the time to fork, but right now I'm getting a "Too many children" error ;) 
I'll keep this in mind, should I suddenly find myself with some time on my hands, so please post again, should you solve it.

**Comment by bobthecow** [comment]
Too many children? I haven't seen that one. Paste me a file and I'll take a look.

**Comment by Ibmurai** [comment]
Erm... The "Too many children" error occurs in my life and not in Coda... I'm sorry that my humor mislead you.

**Comment by bobthecow** [comment]
Ahh. I'm not normally this slow. I spent all day eating fried food on a stick in the sun at the Minnesota State Fair. I'm blaming the two dozen fresh cookies and all you can drink milk :)

-- justin
