### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by Amparose** [bobthecow/Markdown.mode#3]
Renamed `Contents/` to `Markdown.mode` and put it in the Modes/ folder. Open a .md file and there's no syntax highlighting. It also ins't in Text > Syntax Mode.

_Step 3: ?_ definitely happens.

_Step 4: Profit!_ definitely does not happen.

**Comment by bobthecow** [comment]
That's because you made up an entirely new step :)

The whole repo (not just the Contents) folder is Markdown.mode.

**Comment by Amparose** [comment]
Lies! Subterfuge! Shady corruption!

Actually you're right and it should be obvious from the folder name... No profit for me!
